Store response in redis cache instead of sqlite db

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -24,7 +24,7 @@
 #######################################
 
 valid_environments=("production" "testing" "development")
-required_variables=("ENVIRONMENT")
+required_variables=("ENVIRONMENT" "REDIS_URL")
 
 #######################################
 #####      Internal functions     #####
@@ -86,19 +86,19 @@ _check_required_variables() {
 #####      Exposed functions     #####
 ######################################
 check_db() {
-	docker compose -f docker-compose."$ENVIRONMENT".yml run backend /bin/sh -c "test -f /app/instance/${ENVIRONMENT}.db && (exit 0) || (exit 1)"
-	exit_code=$?
+    docker compose -f docker-compose."$ENVIRONMENT".yml run backend /bin/sh -c "test -f /app/instance/${ENVIRONMENT}.db && (exit 0) || (exit 1)"
+    exit_code=$?
 
-	if [[ "$exit_code" = 0 ]]; then
-		echo "Database found"
-	else
-		echo "Database not found. Run migrations first" && exit 1
-	fi
+    if [[ "$exit_code" = 0 ]]; then
+        echo "Database found"
+    else
+        echo "Database not found. Run migrations first" && exit 1
+    fi
 }
 
 start() {
     echo "Starting containers in $ENVIRONMENT environment"
-    check_db && DEBUG=$_arg_debug docker compose -f docker-compose."$ENVIRONMENT".yml up -d frontend backend db
+    check_db && DEBUG=$_arg_debug docker compose -f docker-compose."$ENVIRONMENT".yml up -d frontend backend db redis
 }
 
 stop() {
@@ -110,7 +110,7 @@ build() {
 }
 
 connect_service() {
-	ENVIROMENT=${ENVIRONMENT} docker compose -f docker-compose."$ENVIRONMENT".yml run -it "$_arg_connect_service" /bin/sh
+    ENVIROMENT=${ENVIRONMENT} docker compose -f docker-compose."$ENVIRONMENT".yml run -it "$_arg_connect_service" /bin/sh
 }
 
 ps() {
@@ -131,9 +131,9 @@ tests() {
     start && docker compose -f docker-compose."$ENVIRONMENT".yml exec backend pytest tests -vvv
 }
 
-
 isession() {
-    docker compose -f docker-compose."$ENVIRONMENT".yml run --rm isession
+    docker compose -f docker-compose."$ENVIRONMENT".yml up -d isession &&
+        docker attach $(docker ps -aqf "name=isession")
 }
 
 init_db() {
@@ -141,21 +141,21 @@ init_db() {
 }
 
 start_cert_server() {
-    docker compose -f docker-compose.certbot.yml down && \
-	docker compose -f docker-compose.certbot.yml up -d nginx80
+    docker compose -f docker-compose.certbot.yml down &&
+        docker compose -f docker-compose.certbot.yml up -d nginx80
 }
 
 stop_cert_server() {
-	docker compose -f docker-compose.certbot.yml down
+    docker compose -f docker-compose.certbot.yml down
 }
 
 get_certificate() {
-	docker compose -f docker-compose.certbot.yml run --rm  certbot certonly --webroot \
-		--webroot-path /var/www/certbot/ --dry-run -d www.$(DOMAIN) -d $(DOMAIN) -v
+    docker compose -f docker-compose.certbot.yml run --rm certbot certonly --webroot \
+        --webroot-path /var/www/certbot/ --dry-run -d www.$(DOMAIN) -d $(DOMAIN) -v
 }
 
 renew_certificate() {
-	docker compose -f docker-compose.certbot.yml run --rm  certbot renew --webroot --webroot-path /var/www/certbot/
+    docker compose -f docker-compose.certbot.yml run --rm certbot renew --webroot --webroot-path /var/www/certbot/
 }
 
 install_backend() {
@@ -168,7 +168,6 @@ install_backend() {
     start && docker compose -f docker-compose."$ENVIRONMENT".yml exec backend \
         pip install "$_arg_install_backend"
 }
-
 
 ## Check for environment variables
 
@@ -222,30 +221,28 @@ begins_with_short_option() {
 _arg_connect_service=
 _arg_debug="off"
 
-print_help()
-{
-	printf '%s\n' "The general script's help msg"
-	printf 'Usage: %s [--start] [--stop] [--print-vars] [--build] [--(no-)debug] [--tests] [--ps] [--logs] [--check-db] [--isession] [--init-db] [--start-cert-server] [--stop-cert-server] [--get-certificate] [--renew-certificate] [--connect-service <arg>] [--install-backend <arg>] [-h|--help]\n' "$0"
-	printf '\t%s\n' "--start: Start the server"
-	printf '\t%s\n' "--stop: Stop the server"
-	printf '\t%s\n' "--print-vars: Print variables"
-	printf '\t%s\n' "--build: Build containers"
-	printf '\t%s\n' "--debug, --no-debug: Start up the debugging server and attach (off by default)"
-	printf '\t%s\n' "--tests: Run pytests"
-	printf '\t%s\n' "--ps: Print running containers"
-	printf '\t%s\n' "--logs: Tail out logs"
-    printf '\t%s\n' "--check-db: Check of database exists" 
-	printf '\t%s\n' "--isession: Start an interactive session"
-	printf '\t%s\n' "--init-db: Initialize the database"
-	printf '\t%s\n' "--start-cert-server: Start the certbot server on port 80"
-	printf '\t%s\n' "--stop-cert-server: Stop the certbot server"
-	printf '\t%s\n' "--get-certificate: Get a certbot certificate"
-	printf '\t%s\n' "--renew-certificate: Renew certificate"
-	printf '\t%s\n' "--connect-service: Connect to a service (default: 'connect-service')"
-	printf '\t%s\n' "--install-backend: Install backend package (no default)"
-	printf '\t%s\n' "-h, --help: Prints help"
+print_help() {
+    printf '%s\n' "The general script's help msg"
+    printf 'Usage: %s [--start] [--stop] [--print-vars] [--build] [--(no-)debug] [--tests] [--ps] [--logs] [--check-db] [--isession] [--init-db] [--start-cert-server] [--stop-cert-server] [--get-certificate] [--renew-certificate] [--connect-service <arg>] [--install-backend <arg>] [-h|--help]\n' "$0"
+    printf '\t%s\n' "--start: Start the server"
+    printf '\t%s\n' "--stop: Stop the server"
+    printf '\t%s\n' "--print-vars: Print variables"
+    printf '\t%s\n' "--build: Build containers"
+    printf '\t%s\n' "--debug, --no-debug: Start up the debugging server and attach (off by default)"
+    printf '\t%s\n' "--tests: Run pytests"
+    printf '\t%s\n' "--ps: Print running containers"
+    printf '\t%s\n' "--logs: Tail out logs"
+    printf '\t%s\n' "--check-db: Check of database exists"
+    printf '\t%s\n' "--isession: Start an interactive session"
+    printf '\t%s\n' "--init-db: Initialize the database"
+    printf '\t%s\n' "--start-cert-server: Start the certbot server on port 80"
+    printf '\t%s\n' "--stop-cert-server: Stop the certbot server"
+    printf '\t%s\n' "--get-certificate: Get a certbot certificate"
+    printf '\t%s\n' "--renew-certificate: Renew certificate"
+    printf '\t%s\n' "--connect-service: Connect to a service (default: 'connect-service')"
+    printf '\t%s\n' "--install-backend: Install backend package (no default)"
+    printf '\t%s\n' "-h, --help: Prints help"
 }
-
 
 parse_commandline() {
     while test $# -gt 0; do
@@ -266,7 +263,7 @@ parse_commandline() {
             build
             exit 0
             ;;
-        --no-debug|--debug)
+        --no-debug | --debug)
             _arg_debug="on"
             test "${1:0:5}" = "--no-" && _arg_debug="off"
             ;;
@@ -283,9 +280,9 @@ parse_commandline() {
             exit 0
             ;;
         --check-db)
-			check_db
-			exit 0
-			;;
+            check_db
+            exit 0
+            ;;
         --isession)
             isession
             exit 0
@@ -301,9 +298,9 @@ parse_commandline() {
             _arg_connect_service="${_key##--connect-service=}"
             ;;
         --init-db)
-				init_db
-				exit 0
-				;;
+            init_db
+            exit 0
+            ;;
         --start-cert-server)
             start_cert_server
             exit 0
